version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: eventplaner_db
    environment:
      POSTGRES_DB: eventplaner_db
      POSTGRES_USER: eventplaner_user
      POSTGRES_PASSWORD: user
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d  # SQL-Skripte werden automatisch ausgeführt
    ports:
      - "5432:5432"
    networks:
      - eventplaner_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: eventplaner_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@eventplaner.at
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - eventplaner_net
    depends_on:
      - postgres

  app:
    build: .
    container_name: eventplaner_app
    ports:
      - "1220:1220"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/eventplaner_db
      SPRING_DATASOURCE_USERNAME: eventplaner_user
      SPRING_DATASOURCE_PASSWORD: user
    networks:
      - eventplaner_net
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  eventplaner_net:
    driver: bridge